### ISSUE TITLE
Defining postgres schemas not working

### ISSUE THREAD

**Issue by tsh356** [motor-admin/motor-admin#101]
Defining postgres schemas aren't working here:

![image](https://github.com/motor-admin/motor-admin/assets/7598315/be2a218c-81f3-4be1-b854-c0b0d97a5eeb)

The form submits successfully, but on reload the Schemas field is blank and the app still  loads only public schema.

As a test, I downgraded to `image: motoradmin/motoradmin:0.3.16` and it works properly.

**Comment by omohokcoj** [comment]
@tsh356 thnaks for reporting this bug - it has been fixed in the latest 0.4.19 release
