### ISSUE TITLE
Motor Admin hides the resource for unknown reason, based on name maybe?

### ISSUE THREAD

**Issue by roelvlk** [motor-admin/motor-admin#102]
I've been debugging my DB config for a while, changed PK config etc etc to get this working, but in the end it turns out that if your table name is "company", the UI does not show this as a resource? There is no way to add it manually as resource when that happens.

To test the access from Motor Admin to the DB, I have entered a query in the reports panel : SELECT * FROM company and it just showed me the table, so the access and connection are OK. Any idea what can be the root cause of this? Is Motor Admin using an internal Company table for rights and roles (on its own DB) but does it trigger this behavior? Or maybe another config that I got wrong and just changed by changing names? I'm on Postgres DB from Supabase.
Thanks for checking. 

Here are some other tables that show up, for example company_role : 

<img width="210" alt="Screenshot 2023-06-22 at 15 44 31" src="https://github.com/motor-admin/motor-admin/assets/137415157/39a24a18-f946-4570-8968-ad7c7f16b640">

I only noticed my company table showing up as a resource in Motor Admin when I changed it to company_old for example, then it shows up in this list as "Company Olds". Bringing the table name back to Company, again deletes the resource from Motor Admin.

**Comment by omohokcoj** [comment]
@roelvlk unfortunately i was not able to reproduce the bug: `create table company (id int primary key, name text);
` is displayed in motor admin.
This bug might be somehow related to your specific tables/columns - there should be error logs regarding your 'company' table when you boot motor admin and load resources for the first time  - maybe it will help to identify the issue
