### ISSUE TITLE
Variable Support in Queries

### ISSUE THREAD

**Issue by MarleTangible** [motor-admin/motor-admin#108]
Hello,

Great project, thank you. I have a quick question. Is there a built-in variable support in queries? I'm trying to create a query where a certain column is equal to the currently logged in user's email address or name etc. I'm trying to create a report where each user only sees things that are related to them.

Sincerely,

**Comment by omohokcoj** [comment]
@MarleTangible yep, {{ current_user_id }} and {{ current_user_email }} variable are available in SQL queries:
![image](https://github.com/motor-admin/motor-admin/assets/5418788/371f7d8c-7a45-49d2-85a5-7b361f1c3a95)

**Comment by MarleTangible** [comment]
Awesome! Thank you. @omohokcoj 

For anyone who's interested, you should first run a sample query to see the settings button and then the side panel can be used to discover information about the variables.
