### ISSUE TITLE
More filter conditions for Long text & Richtext

### ISSUE THREAD

**Issue by arnaud** [motor-admin/motor-admin#11]
Creating advanced filters for `Text` columns works pretty well, one having the luxury to choose from multiple filter conditions:

> ![image](https://user-images.githubusercontent.com/44078/140822652-b459facb-5258-4fdb-acbf-0c80db00d37b.png)

However, the filter conditions list is rather sparse for `Long text`, `Richtext`:

> ![image](https://user-images.githubusercontent.com/44078/140822404-0836dfee-9731-4a8e-a8f5-2f29b644c97e.png)

And one could wonder why? 🧐

| :heart: kudos to a very well executed full-fledged auto-generated admin panel solution |
|-|

**Comment by omohokcoj** [comment]
Thanks @arnaud it has been fixed in the newest version:
You can learn about how to upgrade to the latest version here:
https://github.com/motor-admin/motor-admin/releases/tag/latest

**Comment by arnaud** [comment]
thanks!
