### ISSUE TITLE
Custom filters on queries

### ISSUE THREAD

**Issue by brauliobo** [motor-admin/motor-admin#110]
Currently, queries are static views without the possibility of filtering data. It would be nice to configure parameters on queries (for instance using interpolation - %{param} -, ERB, etc) and then add them as filters to the query and to the dashboards.

Filters could be of multiple types. Initially they could be just be of fields of a table, just like resources have

**Comment by omohokcoj** [comment]
@brauliobo i believe this already exists in motor admin - you can use variables in SQL queries ({{variable}}) and the those variables will be show as filters at the top of SQL query.

![image](https://github.com/motor-admin/motor-admin/assets/5418788/ee0c889e-752b-4b43-ad6e-6f0d528859c8)
