### ISSUE TITLE
Customise Data Display

### ISSUE THREAD

**Issue by manamelacedric** [motor-admin/motor-admin#112]
Hi everyone,

Is there a say I can customize the way the data is displayed on the admin UI?

I have a use case where boolean data is stored in the DB as 1/0, and I would like to display them as True/False or Yes/No.

Please assist.

Thanks.

**Comment by omohokcoj** [comment]
@manamelacedric you can simply adjust your resource SQL query to convert 1/0 to yes/no or else.
https://docs.getmotoradmin.com/guide/customizing_resource_table.html#demo
