### ISSUE TITLE
Removing Motor Admin

### ISSUE THREAD

**Issue by ashkanyadegari** [motor-admin/motor-admin#113]
Hi guys,

I really love motor admin, I think one of the best things someone pushed out for auto generated admin panels. However, I am ready to build my own admin panel since I have some specific needs.

I was wondering how I can remove motor admin from my rails app? Since there is a migration file nested between the rest of my migration files, not sure what to do.

**Comment by omohokcoj** [comment]
@ashkanyadegari you can simply revert motor admin migrations:
`rake db:migrate:down VERSION=<version of motor admin migration>`
