### ISSUE TITLE
How do custom action types work?

### ISSUE THREAD

**Issue by MarleTangible** [motor-admin/motor-admin#120]
How can I create a method and assign it to an action? Thank you.

The demo has an action named "Mark as Shipped" that uses an action type of "Method Call" but I haven't been able to create something similar with the Docker example. Is this feature limited to Pro version only?

![image](https://github.com/motor-admin/motor-admin/assets/107574310/ec89cbe9-01b4-47ed-a66c-c192722cbe9b)

**Comment by umerfarooq** [comment]
This has been asked for quite some time now but I'll put in my comments for anyone who may still be looking for this.

Custom Actions, is a feature available in the Free version. For an Action Type = Method Call, there needs to be a function/method defined in the corresponding Model to be mapped. I hope this helps!

**Comment by MarleTangible** [comment]
@umerfarooq 
When you say a function/method needs to be defined in the model, you mean in the database? The description of a very basic example would go a long way. And also, thank you for your response.

**Comment by umerfarooq** [comment]
> @umerfarooq When you say a function/method needs to be defined in the model, you mean in the database? The description of a very basic example would go a long way. And also, thank you for your response.

@MarleTangible No, I meant it needs to be defined in the Model corresponding to the Resource you are customizing. See the screenshots attached, as to how I mapped a Custom Method.

<img width="1003" alt="Screenshot 2024-12-23 at 5 41 28 PM" src="https://github.com/user-attachments/assets/88dbf917-c551-43fc-8426-b120a8e20d60" />

![custom-action-motor-admin](https://github.com/user-attachments/assets/81fe341d-ad30-455b-947f-b94ab35551f5)

**Comment by MarleTangible** [comment]
Awesome. Thank you!
