### ISSUE TITLE
PG int arrays display

### ISSUE THREAD

**Issue by jcsrb** [motor-admin/motor-admin#14]
I have this PG field

```
example integer[] DEFAULT '{}'::integer[]
```

it is correctly identified as integer 

in the single view it gets displayed as
<img width="153" alt="Screenshot 2021-11-12 at 00 36 46" src="https://user-images.githubusercontent.com/119011/141378914-5c9cf674-0bb6-43c6-bede-0f81d053e421.png">

`character varying[]` fields work as expected.

**Comment by omohokcoj** [comment]
Thanks @jcsrb  it has been fixed in the newest version.
You can learn about how to upgrade to the latest version here:
https://github.com/motor-admin/motor-admin/releases/tag/latest
