### ISSUE TITLE
configure cors

### ISSUE THREAD

**Issue by ykorzikowski** [motor-admin/motor-admin#18]
Hey there, 

first thank you for the great work :) I really like your tool. 

I want to set up motor admin with some https nginx proxy, but I get the following error: 

```
W, [2021-11-17T15:30:31.807601 #1]  WARN -- : [0da10b23-eca1-4445-8a5b-c7aa7029a279] HTTP Origin header (https://*****olutions.eu) didn't match request.base_url (http://****olutions.eu)
I, [2021-11-17T15:30:32.030903 #1]  INFO -- : [0da10b23-eca1-4445-8a5b-c7aa7029a279] {"method":"POST","path":"/sign_in","status":422,"duration":223.71,"view":0.0,"db":0.0,"fwd":"192.168.178.131","uid":1}
F, [2021-11-17T15:30:32.031586 #1] FATAL -- : [0da10b23-eca1-4445-8a5b-c7aa7029a279]
[0da10b23-eca1-4445-8a5b-c7aa7029a279] ActionController::InvalidAuthenticityToken (HTTP Origin header  (https://*****olutions.eu) didn't match request.base_url  (https://*****olutions.eu)):
```
Changing the `BASE_URL`parameter seems not working and result in other errors.

**Comment by omohokcoj** [comment]
Hi @ykorzikowski, I think you might need to add extra proxy headers to your ngix configs to make it work:
https://github.com/rails/rails/issues/22965#issuecomment-172929004
I will investigate if it's possible to make it work without those proxy headers but for now it's probably the only solution.

**Comment by ykorzikowski** [comment]
Thank you :) this solves my problem. So should we leave the ticket open or close it?

**Comment by omohokcoj** [comment]
Thanks @ykorzikowski I will create a new .md file in /guides regarding the proxy configurations so other people can use it from there 😃
