### ISSUE TITLE
Problem with sign_in and different BASE_PATH set than /

### ISSUE THREAD

**Issue by ykorzikowski** [motor-admin/motor-admin#19]
Scenario: 

motor admin is both reachable with this url: 

```
https://dev.***utions.eu/motor
and
http://docker.****tions.eu:3210/
```

Requesting `https://dev.***utions.eu/motor` results in `https://dev.***utions.eu/sign_in` which result in 404 because nginx dont route this url to motor. 

Requesting `http://docker.****tions.eu:3210/` results in error (okay because motor is missing)

Requesting `http://docker.****tions.eu:3210/motor` redirects to `http://docker.****tions.eu:3210/sign_in` which should not be okay, but its working login form. It logs in and i can start working. 

Can be work-arounded by following nginx snippet: 

```
   location /sign_in {
        proxy_pass http://docker.****ions.eu:3210/sign_in;
        client_max_body_size 10M;
        proxy_set_header  Host $host;
        proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header  X-Forwarded-Proto $scheme;
        proxy_set_header  X-Forwarded-Ssl on; # Optional
        proxy_set_header  X-Forwarded-Port $server_port;
        proxy_set_header  X-Forwarded-Host $host;
   }
```

So the problem is: `sign_in`routing ignores BASE_URL env.

**Comment by omohokcoj** [comment]
@ykorzikowski are you using the latest version?
It's true that there was a bug with the /sign_in ignoring BASE_PATH in previous versions but in has been fixed in the latest version:
![image](https://user-images.githubusercontent.com/5418788/142610295-721f4fea-a73d-4d3a-8d2d-4deaf87667b0.png)
The latest docker image redirects to /admin/sign_in when base path is set to /admin

**Comment by ykorzikowski** [comment]
yes you are right. normally I do docker pulls on mondays :D

thx for the fix

**Comment by HamedAkhavan** [comment]
@omohokcoj what about static files, they're still loaded from root path instead of BASE_PATH, is there any other ENV I should set for that?
ps: I've set BASE_PATH=/motoradmin but for example this js file is loaded from _/packs/js/application-6e930326bb811b78e291.js_
