### ISSUE TITLE
SQL error when extending default SQL queries

### ISSUE THREAD

**Issue by arnaud** [motor-admin/motor-admin#21]
Extending the SQL query in the query editor makes it unusable since motoradmin version `0.2.19`.

#### Default query

```sql
SELECT "schema"."mytable".* FROM "schema"."mytable"
```

#### Modified query

```sql
SELECT "schema"."mytable".*, 'so meta' as complimentary_field FROM "schema"."mytable"
```

#### Result

The table listing doesn't work; no data is fetched.

When investigating with `Postgres 12.4` we discover the following error:

> ERROR:  syntax error at or near "."
> LINE 1: ....*, 'so meta' as complimentary_field FROM "schema"."mytable") AS schema.mytable...

Which is heavily linked to how the associated query is generated:

#### Generated query

```sql
SELECT "schema"."mytable".* FROM (
  SELECT
    "schema"."mytable".*,
    'so meta' as complimentary_field FROM "schema"."mytable"
) AS schema.mytable -- 👈
ORDER BY "schema"."mytable"."name" ASC
LIMIT $1 OFFSET $2;
```

**Comment by omohokcoj** [comment]
@arnaud this issue was caused by your custom schema name (which is not a "public" schema).
The newest version contains a way to specify pg schemas via DB configurations - so you need to specify your schema name there and restart the app to fix the issue:
<img width="945" alt="image" src="https://user-images.githubusercontent.com/5418788/143428470-04186284-131d-4c53-ac28-6d5de67ae24c.png">

**Comment by arnaud** [comment]
I see. Sadly, the latest current version for the Docker image is still stuck to `0.2.26` :(

**Comment by omohokcoj** [comment]
@arnaud new docker images have been uploaded to docker hub - please give it another try 😄

**Comment by arnaud** [comment]
Thanks for the push.

Actually, the issue still persists with the latest version (`0.2.31`).

```
ERROR:  syntax error at or near "."
LINE 1: ...omments) hashtags FROM "mytable") AS schema.mytable LIM...
                                                      ^
```

**Comment by omohokcoj** [comment]
Did you put your custom schema name into the schemas field on the DB configs page from the screenshot above?
Also you need to restart the server in order to apply this change.
@arnaud

**Comment by arnaud** [comment]
A server restart did the trick! Thank you so much! Support is _very_ appreciated 🙏
