### ISSUE TITLE
Is it possible to create a Cohort analysis?

### ISSUE THREAD

**Issue by silva96** [motor-admin/motor-admin#25]
Given an orders table, create a cohort analysis to see the percent of users from each cohort are coming back in the next periods

I believe the motor has the potential to do so, using  tables but i cant come up with the proper query

This is how it should look like

![IMG_20211202_134453](https://user-images.githubusercontent.com/4019924/144465564-7fa44756-8479-44cf-8747-9bc48340443f.jpg)

Can you help me please ?

**Comment by omohokcoj** [comment]
@silva96 the newest version of ruby gem allows to create report queries using data from APIs:
https://rubygems.org/gems/motor-admin/versions/0.2.33

So you can integrate your existing HTML reports with motor admin or implement a new cohort report as a simple HTML table and integrate it with motor admin via API query reports.
For now, it's the only option - it's quite hard to build a precise cohort report using pure SQL but it should be doable with rails via API queries.

**Comment by silva96** [comment]
Great! Thanks a lot
