### ISSUE TITLE
How to handle version control (git)

### ISSUE THREAD

**Issue by ilijaNL** [motor-admin/motor-admin#29]
Hello, I just discovered this project and the approach is used is far better than other alternatives. However is there a possibility to version control this? And how to handle different environments, say I have a develop environment and I want to move everything to production?

Thanks

**Comment by omohokcoj** [comment]
@ilijaNL it's possible to use git to version configurations in motor-admin.yml file and transfer them with different remote ends via git push.
Alternatively it's possible to use a built-in `motor-admin sync` command to sync configs between environments.
You can learn a bit more about it here:
https://github.com/motor-admin/motor-admin/blob/master/guides/configurations_sync_between_environments.md

It should work in the latest version with all motor admin configs except users and roles - those should be transferred manually for security reasons.

**Comment by ilijaNL** [comment]
@omohokcoj thanks for your answer. Is it possible to mount the motor-admin.yml config inside docker such that the configuration is automatically synced? 

I just wondering what the best approach is to start motor admin inside docker (or docker compose) which has automatically has the latest config

**Comment by omohokcoj** [comment]
@ilijaNL I updated the docker image with mounted volume for config files - you can find some info here:
https://github.com/motor-admin/motor-admin/blob/master/guides/configurations_sync_between_environments.md#docker-git
Current working directory is automatically mounted via `docker compose up` but for `docker run` you might need to mount it with `-v `pwd`:/app`
To update the image you need to run `docker pull motoradmin/motoradmin:latest` or `docker compose up --force-recreate`
Let me know if it solves the issue.

**Comment by omohokcoj** [comment]
@ilijaNL closing this assuming my previous comments helped to resolve the issue.
