### ISSUE TITLE
How to setup images

### ISSUE THREAD

**Issue by irisjae** [motor-admin/motor-admin#31]
Hi @omohokcoj ! I haven't been able to setup images with Motor admin so far.

I've tried peeking at the demo to understand how to set it up, and I've attempted several options to no avail. I've found that in the demo dashboard, even though the Product resource has images, the table itself doesn't appear to have it has a column, so I attempted to directly add a new column with the type of Image to my resource, but then it gives me "column_name" is not an attribute. If I then change my table schema to include "column_name" as a column, then it goes through. But then when I upload an image when I create a new row, the image doesn't appear to work. No row is created on the Attachments resource, and I only find the value '{"filename"=>"image 18.png", "io"=>#<StringIO:0x000000000b6187e8>}' in the column for the image.

Thanks for any guidance on how to set it up!

**Comment by omohokcoj** [comment]
Hi @irisjae ! You can learn more about image/file attachments here:
https://github.com/motor-admin/motor-admin/blob/master/guides/file_attachments.md
Please let me know if this solves the issue.

**Comment by irisjae** [comment]
Thank you for the quick response! Unfortunately when I try the method of setting a Reference to Attachment from the linked doc, I simply get a null in the image column. I'm not sure whats happening. Is there any information I should provide to help you understand the situation?

**Comment by omohokcoj** [comment]
@irisjae I think you need to remove the `image` column from the database you added previously - and start adding the reference attachment column from scratch (also might need to restart the server after you remove the column).

**Comment by irisjae** [comment]
@omohokcoj Oh yes that seems to have done the trick! Thank you!

**Comment by irisjae** [comment]
@omohokcoj Also may I ask that given that the image is not stored directly in my table, but rather the "active_storage_attachments" table, how would you advise my application to fetch the URL for the image from the database? I do not seem to find the Blob information in the "active_storage_attachments" either.

**Comment by omohokcoj** [comment]
@irisjae there are no easy ways to get image url when they are stored on local disk in folder.
But for aws s3 all files are stored in s3 bucket using active storage blob key  so you can use blob key column to build aws s3 url.
Also you might need to setup public access to aws s3 bucket like described here:
https://stackoverflow.com/questions/64705596/how-do-i-set-my-aws-s3-rails-5-2-activestorage-to-public
Let me know if it helped to resolve the issue.

**Comment by irisjae** [comment]
@omohokcoj Alright, I guess I can find the local file location via the "active_storage_blobs" table. I can't seem to find a good way to generate the image URL out of Rails, so I'll have to spin up a separate image server. Thanks again!
