### ISSUE TITLE
View resources / tables generated by another ORM

### ISSUE THREAD

**Issue by laloweb99** [motor-admin/motor-admin#32]
Hello! I'm trying to view the tables created by an application that uses [Gorm](https://gorm.io/) as resources. But motor admin doesn't show them and I cannot find how to add a resource to the motor admin. Is there guide for this? Thank you.

**Comment by omohokcoj** [comment]
Hi @laloweb99 - motor admin should display all tables which are present in your postgresql database automatically.
If you have some custom sql view in your Gorm application then you probably need to copy that sql code into motor admin queries to display it there.

**Comment by laloweb99** [comment]
I have the "papers" table on the public schema but is not being shown on motor admin. I'm running the docker compose. Is there a way to sync the tables on moto admin? 
![image](https://user-images.githubusercontent.com/70488247/146687619-296ab621-e280-43b5-9b32-7c79af3f9fb2.png)

![image](https://user-images.githubusercontent.com/70488247/146687627-cb71a850-1b8a-4327-a7c2-ba40fe95ab05.png)

**Comment by omohokcoj** [comment]
@laloweb99 it seems like you are using the same docker compose postgresql for motor admin configuration tables and for application data tables.
You need to make sure that motor admin is connected to the same docker compose database with papers table here (if that's what is intended):
http://localhost:3000/settings/database 

But usually application data should be stored in a separate database (meaning that your papers table won't be in the same database with motor_admin_users table) - you can specify databases using this link http://localhost:3000/settings/database (might require to restart a server).

Please let me know if this solves the issue.

**Comment by laloweb99** [comment]
I moved the paper table to an app database but it's still not showing the "papers" resource: 

DB config on motor admin
![image](https://user-images.githubusercontent.com/70488247/146688335-dcf7243f-d388-4ab5-afc5-b36f8f2fbcc7.png)

Tables on app databse
![image](https://user-images.githubusercontent.com/70488247/146688347-f30cc459-23fe-46fd-8ab5-6df4a3b541ef.png)

Resources shown in motor admin
![image](https://user-images.githubusercontent.com/70488247/146688377-1b5b6e12-80c4-48c3-8fd0-b2459ce74c40.png)

**Comment by omohokcoj** [comment]
@laloweb99 apparently the table was not visible because it didn't contain a primary key.
This bug has been fixed in the latest 0.2.38 release - you can update your docker image with `docker pull motoradmin/motoradmin:latest`

**Comment by laloweb99** [comment]
Now it shows the table :smile:  thank you so much!
