### ISSUE TITLE
sqllite

### ISSUE THREAD

**Issue by Code-Slave** [motor-admin/motor-admin#33]
I see if you dont define a db on startup it creates an sqlite db. is there a way to connect to sqllite from the start. I just see mysql and pg?

**Comment by omohokcoj** [comment]
@Code-Slave motor admin creates sqlite database for internal configurations.
Usually application data is stored in pg/mysql/sqlserver and can be accessed via database URL specified in the UI during the setup process.
Are you using sqlite for you application data to build motor admin admin panel on top of it?

**Comment by Code-Slave** [comment]
Yes id like to use it for sqlite dbs the same as mysql and pg. i have sqlite dbs that are a couple hundred gigs that id love to use this with

**Comment by omohokcoj** [comment]
@Code-Slave the latest version of motor admin allows to use sql database - in order to connect to sqlite database you need to create a `database.sqlite3` symlink to the database sqlite3 file in motor admin project root directory.
Let me know if this solves the issue.

**Comment by Code-Slave** [comment]
Thanks. It will be a couple days. Im one of the lucky ones in the east coast us winter storm with no power going on day 2.
