### ISSUE TITLE
Remove default order by id desc when a scope sets an specific order

### ISSUE THREAD

**Issue by silva96** [motor-admin/motor-admin#34]
Currently I have a scope on Posts called "most_commented" which orders by `comments_count desc` but when selecting that scope in the admin panel, it prepends an order by `id desc` before so giving precedence to the actual selected scope.

I can click on the id column and it takes away the default id order. ButI have to do it everytime for every sope that has an order.

**Comment by omohokcoj** [comment]
@silva96 it has been fixed in the latest release:
https://rubygems.org/gems/motor-admin
btw you can report rails-related issues in motor-admin-rails repo
