### ISSUE TITLE
Loading form data results in 401

### ISSUE THREAD

**Issue by ykorzikowski** [motor-admin/motor-admin#36]
Using the latest version of motor admin (0.2.57), docker release

Create request will use Authorization
![Bildschirmfoto 2022-02-08 um 12 38 09](https://user-images.githubusercontent.com/20556547/152994819-4e73c8d8-433e-4bdb-bdd6-f5a57bf112af.png)

Fetching form data has no authorization header
![Bildschirmfoto 2022-02-08 um 12 44 23](https://user-images.githubusercontent.com/20556547/152994789-250bc3f2-7f6c-41bd-8cfd-5c1f853f9f2b.png)

**Comment by omohokcoj** [comment]
@ykorzikowski thanks for reporting this - it has been fixed in the latest 0.2.61 release.
