### ISSUE TITLE
Schemas

### ISSUE THREAD

**Issue by DeolTito** [motor-admin/motor-admin#38]
Hello,

I've deployed motoradmin on my container and it worked fine. However, I encountered an issue while switching the schemas under it. By default, they have fetched the tables under the public at first and when I tried to change the schema from public to one of my custom one, the tables aren't listed. I've decommissioned the container and started from scratch. During the initial process, I've tried adding the custom schema and fetched the tables. But again,we won't be able to add a new scheme. 

Is there any solution for this?

**Comment by omohokcoj** [comment]
@DeolTito try to restart motor admin container in order to make the schema change take affect.

**Comment by DeolTito** [comment]
> @DeolTito try to restart motor admin container in order to make the schema change take affect.

Does that mean, we will have to restart the container all the time if we wish to add a new schema?

As the volume is mapped on to the host machine, I don't think restarting the container would have any affect as it will pull same contents again.

**Comment by omohokcoj** [comment]
@DeolTito defined schemas are a part of postgresql DB connection URL - motor admin doesn't record to apply new schemas automatically - you need to restart motor admin server so it connects to the DB with new schemas.

**Comment by DeolTito** [comment]
> @DeolTito defined schemas are a part of postgresql DB connection URL - motor admin doesn't reconnect to apply new schemas automatically - you need to restart motor admin server so it connects to the DB with new schemas list.

Can we add multiple schemas at once?

I've tried that most of the tables weren't fetched.

**Comment by DeolTito** [comment]
> @DeolTito you can specify all your schemas separated with comma - "schema_one,schema_two"

Yes, I've tried that already but all the tables are fetched from the remote server.

That said, are you talking about restarting the whole server/container for adding the new schema or just a particular service under it?

**Comment by omohokcoj** [comment]
@DeolTito the whole container should be restarted - docker restart container_name
You can simply try it on your local dev machine - it should work there.
If you deployed it straight to some containers service then you need to find some way to restart containers there.

**Comment by DeolTito** [comment]
> @DeolTito the whole container should be restarted - `docker restart container_name` You can simply try it on your local dev machine - it should work there. If you deployed it straight to some containers service then you need to find some way to restart containers there.

That worked.

Just to confirm, does Motoradmin support only Postgres, Mysql and Microsoft SQL servers?

**Comment by omohokcoj** [comment]
@DeolTito yep only mysql/postgres/sqlserver for now
