### ISSUE TITLE
Date Input Issues

### ISSUE THREAD

**Issue by agusbrand** [motor-admin/motor-admin#40]
Hello,

I'd like to report a bug we had recently, that happens only when using the **Date** input.

When selecting a date in **March 2022**, the input field automatically changes to a date in **Nov 2022**.

- Our Motor Admin version is the latest: **0.2.61**

- I was only being able to replicate this bug after changing my browser's timezone to San Francisco (GMT-8) This was to match the timezone of the users that reported the bug. (It can be changed in dev tools -> sensors)

The bug can be replicated using the live motor admin demo. 

Here is a video:

https://user-images.githubusercontent.com/6878389/157688783-006e7993-b74a-4fed-8dc2-3c8e7df46eed.mov

Thank you!

**Comment by drewbaumann** [comment]
It is an issue on 0.2.62 as well.

**Comment by omohokcoj** [comment]
@agusbrand @drewbaumann it has been fixed in the latest 0.2.63 release

**Comment by agusbrand** [comment]
@omohokcoj Thank you so much!
