### ISSUE TITLE
configure resources inclusively not exclusively

### ISSUE THREAD

**Issue by jamesstaub** [motor-admin/motor-admin#42]
I'm wondering if it's possible to configure my motor.yml to explicitly include a model rather than excluding all the others with 
```
- name: workbook1_arrangement_factory
  preferences:
    visible: false```

I have several hundred models in my app and only want to include a small number of them in this motor admin

**Comment by omohokcoj** [comment]
@jamesstaub unfortunately it's not possible - if you need to exclude many models/tables maybe generating a large yml list to add to motor.yml would be faster than excluding them manually via UI - that's the only option for now.
