### ISSUE TITLE
mysql configuration

### ISSUE THREAD

**Issue by jamesstaub** [motor-admin/motor-admin#43]
I'm having trouble making simple SQL queries in motor admin. a simple query such as `select * from users` shows the error

`Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '__query__ AS (select * from users ) SELECT `__query__`.* FROM `__query__` LIMIT ' at line 1
`

Is there any database configuration necessary in motor.yml?

**Comment by omohokcoj** [comment]
@jamesstaub motor admin uses CTE which is not available in mysql5.7 - the only option is mysql8 or mariadb

**Comment by jamesstaub** [comment]
got it, thanks
