### ISSUE TITLE
Error with mysql database

### ISSUE THREAD

**Issue by DSigmund** [motor-admin/motor-admin#45]
Hi,

im a trying to get the dockerized Version to work with a local mysql-database:

```bash
docker run \
--name somedb-motor \
-v `pwd`:/app \
--env SECRET_KEY_BASE=b4d3076a484320f0affb23c052319ea9110d0069be377239f9ced2f104b9bb3702fa1a57627f9a9fe97737616cdc557ffe4f0bbfb89485d57ffede8fdee84d80 \
--env DATABASE_URL=mysql://somedbuser:somedbpasswd@localhost:3306/somedb \
--restart unless-stopped \
--publish 3000:3000 \
motoradmin/motoradmin:latest
```

But i am  getting this error message:

> /__enclose_io_memfs__/local/config/boot.rb:37:in `require': Could not load the 'mysql' Active Record adapter. Ensure that the adapter is spelled correctly in config/database.yml and that you've added the necessary adapter gem to your Gemfile. (LoadError)

> /__enclose_io_memfs__/local/config/boot.rb:37:in `require': cannot load such file -- active_record/connection_adapters/mysql_adapter (LoadError)

Any Help? Many Thanks in advance :-)

**Comment by omohokcoj** [comment]
@DSigmund try to change db url to 'mysql**2**://'
`mysql2://somedbuser:somedbpasswd@localhost:3306/somedb`

**Comment by agentcobra** [comment]
Hi, 

same for me with mysql or mysql2
![image](https://user-images.githubusercontent.com/1831853/178101414-713a1184-b1e7-4030-a998-250ea8618c06.png)
I'm trying with  Motor Admin v0.2.85 with ubuntu install

**Comment by omohokcoj** [comment]
@agentcobra try to install `apt install -y libmysqlclient-dev` on ubuntu

**Comment by agentcobra** [comment]
@omohokcoj I have another error :
```
root@machine:~# apt install -y libmysqlclient-dev
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances... Fait
Lecture des informations d'état... Fait
Aucune version du paquet libmysqlclient-dev n'est disponible, mais il existe dans la base
de données. Cela signifie en général que le paquet est manquant, qu'il est devenu obsolète
ou qu'il n'est disponible que sur une autre source
Cependant les paquets suivants le remplacent :
  libmariadb-dev-compat libmariadb-dev

E: Le paquet « libmysqlclient-dev » n'a pas de version susceptible d'être installée
```
I have tryed to install  libmariadb-dev-compat libmariadb-dev instead libmysqlclient-dev
but same error 😢

**Comment by omohokcoj** [comment]
@agentcobra did you run `apt update` before install?

**Comment by agentcobra** [comment]
yes, and I'm using bullseye (11.4)

**Comment by agentcobra** [comment]
I'm trying with ```default-libmysqlclient-dev``` but same problem

**Comment by omohokcoj** [comment]
@agentcobra actually Linux executable works only on ubuntu - because of the dynamically linked libraries that are used by the compiled binary. It's possible to make it work on Debian but you need to somehow install the missing linked libraries on your debian VM.
You can check what is missing by running `ldd /tmp/mysql2.so`
Maybe it would be better to try Motor Admin in docker instead - it works perfect on any linux and the deployment process is even easier.

**Comment by agentcobra** [comment]
Hi,
thanks for your anwser,
I cannot use docker because I'm in a lxc container 😄 
but I can help you to adapt motor-admin for debian ;)
```
# ldd /tmp/mysql2.so
        linux-vdso.so.1 (0x00007ffd997cf000)
        libmysqlclient.so.21 => not found
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f330ff85000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f330ff7f000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f330ff62000)
        libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f330fecf000)
        libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f330fbdb000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f330fbbf000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f330fa7b000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f330fa70000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f330f8ab000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f330ffc7000)

```

**Comment by omohokcoj** [comment]
@agentcobra thanks for the ldd output - I recompiled motor-admin with statically linked mysql2 - it should work in debian bullseye now. Try to download the binary from the latest release or from the:
https://github.com/motor-admin/motor-admin/releases/tag/0.2.86

**Comment by agentcobra** [comment]
It's better, the error change.
I will create a specific user without `@` or `/` in password

**Comment by omohokcoj** [comment]
closing this for now assuming the issues has been resolved - that's true that DB url (usually password) can't contain '@' and '/'
