### ISSUE TITLE
Support read api url using environment variable

### ISSUE THREAD

**Issue by revskill10** [motor-admin/motor-admin#5]
Currently when i create a custom form with type API, i must specify directly the api hostname.

I suggest to be able to use environment variable here.

**Comment by omohokcoj** [comment]
thanks, @revskill10 I think a better way to handle that would be via configurations in the UI - let's say there will be another tab in superadmin UI for "Data Sources" to specify and configure APIs from there with credentials to reuse them on custom forms and actions. That's something that is top priority for now in the roadmap - stay tuned :)

**Comment by revskill10** [comment]
@omohokcoj Thanks for such beautiful work. I'm gonna use this to build a reasonable ERP project, so i think there's much more issue from me in future ;).

**Comment by omohokcoj** [comment]
@revskill10 a better way to handle external API has been released - now all external API urls/hosts/credentials are configurable via the Settings UI and can be easily reused on forms/queries.
