### ISSUE TITLE
Customize data view in bar/row graphs

### ISSUE THREAD

**Issue by notfounnd** [motor-admin/motor-admin#50]
Hi, I'd like to know an information about graph visualization.

Is it possible to configure bar or row graphs to show total values (on top and tooltip box) when "stacked" option on?

E.g.:
![image](https://user-images.githubusercontent.com/57534340/174413622-cc21690c-b7b5-4947-8e65-1e74bc54d243.png)

**Comment by omohokcoj** [comment]
@notfounnd thanks for the suggestion - it would be really useful to have the 'total' counters for bar charts.
The problem is that it seems like it's quite hard to do it with charts.js library - i was not able to find an easy way to implement it.
Will return back to this later - hopefully there will be a solution to implement it.

**Comment by notfounnd** [comment]
@omohokcoj no problem, it's my pleasure help the project.

I know performing adjusts like this isn't easy, but in advance, if helps you, I found a plugin specialized in labels for the Chart JS (and a tutorial with how to setup total values at stacked axis graph).

https://chartjs-plugin-datalabels.netlify.app
https://www.youtube.com/watch?v=mlOlkuuh_E8

**Comment by omohokcoj** [comment]
@notfounnd it has been implemented in the 0.2.79 release 😄 
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/5418788/175788633-6d8779db-9c4e-44bc-8e9b-14f04413797b.png">

**Comment by oz123** [comment]
Hi! This is really cool. Can you publish the yaml file with this query?
I am having difficulties understanding how to write queries that actually work with graphs.

**Comment by omohokcoj** [comment]
@oz123 you can use https://demo.getmotoradmin.com/dashboards/1 demo app to check for the chart-sql examples

**Comment by oz123** [comment]
Thank you so much for the quick response!
