### ISSUE TITLE
Radar Chart Possibility Using Chart JS 

### ISSUE THREAD

**Issue by turn0ver** [motor-admin/motor-admin#53]
Hi,

First things first, the power and possibilities of Motor Admin bring to us is huge. So I have a suggestion that I think is going to improve this tool and could bring a huge value (and a differential feature) to that. 

I got on github issues repository that motor admin has a Chart JS engine into your core. This tool has a radar chart option to show some insights about kind of contexts.

Is there a possibility to bring this kind of chart like a default chart into Motor Admin Tool?

Below I am leaving some references about this topic.

https://www.chartjs.org/docs/latest/charts/radar.html

**Comment by omohokcoj** [comment]
@turn0ver radar chart has been added in the latest 0.2.83 release
