### ISSUE TITLE
Has One association missing from show view

### ISSUE THREAD

**Issue by drewbaumann** [motor-admin/motor-admin#54]
An `Order` belongs_to a `Consultation` and a `Consultation` has one `Order`.

We can see this association reflected in the list view for orders, but on the list view for `consultations`, the `order` seems to be missing.
<img width="555" alt="CleanShot 2022-07-25 at 14 30 36@2x" src="https://user-images.githubusercontent.com/337808/180849204-66f1224c-f1d0-41e7-ac17-b9d8d1712dbd.png">

![CleanShot 2022-07-25 at 14 33 37@2x](https://user-images.githubusercontent.com/337808/180849445-c9ebd21d-4300-4d3f-8ea4-ad7cb491ed01.png)

**Comment by omohokcoj** [comment]
@drewbaumann I was not able to reproduce this issue - has_one works in a similar example in the dev app:
<img width="623" alt="image" src="https://user-images.githubusercontent.com/5418788/180853797-06b0d8f1-791d-4251-87ca-285bb4048e8d.png">
<img width="430" alt="image" src="https://user-images.githubusercontent.com/5418788/180853761-8ca2133a-821e-4479-bdfe-bb27d735f43b.png">
<img width="830" alt="image" src="https://user-images.githubusercontent.com/5418788/180853845-0531e4f1-b82c-4500-804d-a09a05ee5a96.png">

Maybe there are some additional options on your has_one association? (default scope, through, custom foreign keys?)

**Comment by drewbaumann** [comment]
It is actually pretty basic:

# Consultation
`has_one :order`

# Order
` belongs_to :consultation, optional: true`

The other main reason I am updating the gem is due to updating our Rails 6 application to Rails 7. Is the demo app running on Rails 6 or Rails 7?

**Comment by omohokcoj** [comment]
It's rails 7 and the latest version of motor admin @drewbaumann

**Comment by drewbaumann** [comment]
🤔. As a next step I will create a branch off our `main` branch to update the motor-admin gem to see if I can replicate this issue in isolation.

**Comment by drewbaumann** [comment]
@omohokcoj So I did some testing of the different gems via trial and error. What I found was that it worked well until version `0.2.83`. I looked at the [diff](https://github.com/motor-admin/motor-admin/compare/0.2.81...0.2.83) and imagine that it is something in this [file](https://github.com/motor-admin/motor-admin/commit/7c7ecd36b820fa744612d42b2980e43f9499585d), but I am not sure what.

**Comment by omohokcoj** [comment]
Thanks @drewbaumann it helped to identify the issue.
So the default pk/fk in has_one configs form were incorrect because of a bug and submitted into your motor.yml 
I released a new version to fix the default values - but you also need to set the correct pk/fk now via the configs UI:
<img width="699" alt="image" src="https://user-images.githubusercontent.com/5418788/180942928-a952a9dc-c9b9-42ce-8726-cb731a8e2df3.png">
So in your case foreign_key should be - consultation_id and primary_key - id

**Comment by drewbaumann** [comment]
That seemed to do the trick! Thank you.
