### ISSUE TITLE
Howto add/remove models from binary on Ubuntu?

### ISSUE THREAD

**Issue by niksfirefly** [motor-admin/motor-admin#55]
I run motor-admin from binary on Ubuntu. 
I cant find any docs and I dont understand how can I create new custom models? how remove existing one such countries,products etc.

regards

**Comment by omohokcoj** [comment]
@niksfirefly motor admin words with databases - so creating a new table in DB (via psql for instance) results in adding a new resource model to the admin UI.
There is a demo on the https://www.getmotoradmin.com that shows how to hide tables from the motor admin UI.

**Comment by niksfirefly** [comment]
OK I found out when I switch to mysql database for data. All resources vanished except attachment and mine are now visible. Thank you for clarification.
But there is another question.
Is there a way to modify standalone motor admin - especially resources  - via ruby/rails code?

**Comment by omohokcoj** [comment]
>Is there a way to modify standalone motor admin - especially resources - via ruby/rails code?
No, it's not possible - for standalone you can use only custom SQL and external APIs to build the admin UI (standalone doesn't know anything about ruby/rails) - but usually you don't need to, since probably any possible customization in the rails gem can be achieved without ruby code in the standalone app.

**Comment by niksfirefly** [comment]
So for example in standalone mode I cant implement cancan?
but it is possible via motor-admin-rails with rails?

**Comment by omohokcoj** [comment]
@niksfirefly yep, in standalone roles/permissions are only in Pro.
In rails open-source you can use cancan for permissions - Rails Pro has users/roles/permissions UI just like the standalone Pro.

**Comment by niksfirefly** [comment]
Thanks for explanation. I think it should be noted somewhere in docs.
regards
