### ISSUE TITLE
Any docs about motor-admin.yml ?

### ISSUE THREAD

**Issue by niksfirefly** [motor-admin/motor-admin#56]
I wonder if there are any docs about  motor-admin.yml ?
Why it t exists? what for? anything?

**Comment by omohokcoj** [comment]
@niksfirefly https://docs.getmotoradmin.com/guide/configurations_sync_between_environments.html

motor-admin.yml exists so developers can commit changes in the admin UI and push into VCS (git).
With this file in VCS other developers can pull the updated motor-admin.yml from VSC to apply the latest changes locally in their dev environment.
Also .yml file can be used to deploy motor admin changes to different environments (staging/prod).

**Comment by TangMonk** [comment]
is motor-admin.yml renamed to motor.yml?
