### ISSUE TITLE
Variables in queries results in: SQLite3::RangeException: column index out of range

### ISSUE THREAD

**Issue by oz123** [motor-admin/motor-admin#57]
I am doing something awfully wrong, I guess. 

![image](https://user-images.githubusercontent.com/1083045/182595156-84fe1022-70bf-41be-969b-0ed0389f2f18.png)

**Comment by oz123** [comment]
Somehow, my SQL is wrong. I am not very literate using SQL directly. 
On the demo site I guess you are using Postgresql and the following works:
```
select name, category from products where category like {{ cat  }} ;
```

![image](https://user-images.githubusercontent.com/1083045/182597928-2832636c-f5fb-441a-bf34-cb75187a64b8.png)


In theory for SQLite this should work, but I still get the above exception.

![image](https://user-images.githubusercontent.com/1083045/182598159-f972c075-efc6-41bd-8eb8-d11df6c4ac86.png)

**Comment by omohokcoj** [comment]
@oz123 there is a bug in SqlLite - it will be fixed in the next release.
But you should probably connect to Mysql or Postgres - SqlLite DB is used only for the demo.

**Comment by oz123** [comment]
I use sqlite extensively in many projects. Can't just move on to PostgreSQL. Can you maybe direct me to the section in the code that tries to run the query and raises the error?
I'm new to rails so I wasn't able to find it.

**Comment by oz123** [comment]
Thank you for the quick fix. I was looking all the time in the wrong place, I didn't realize there is also a separate Gem for this. 

https://github.com/motor-admin/motor-admin-rails/commit/1b8e2c1c8127b40d116917ee8f6b0ddc1e5c9cc2,

I wiil apply the patch locally.

**Comment by oz123** [comment]
The new version works as expected. Thank you so much for being so quick!
