### ISSUE TITLE
Search by reference

### ISSUE THREAD

**Issue by jakubjanousek** [motor-admin/motor-admin#60]
Is it currently possible to search by reference?

Let's say we have the Orders table such as https://motor-admin.herokuapp.com/demo/data/orders and we want to search by user's name that is displayed (ie. Wally). But since the column itself is just an ID, even adding customer to the searchable fields doesn't help.

I guess the workaround is to search customers table and click through associated orders, and that is enough for our case even if it could be be a bit confusing for some of our users that they cannot filter the orders table (or its equivalent in our db) by customer name.

Or is there some way to do it in the current version? Thank you for your answer

**Comment by omohokcoj** [comment]
@jakubjanousek check https://motor-admin.herokuapp.com/demo/data/orders
I added custom SQL with customer_name column - and made it so it uses this column for search.
Also it possible to hid column from the table - but it still will be used in search.

**Comment by jakubjanousek** [comment]
@omohokcoj perfect! That solves our case absolutely. Thanks for the demo
