### ISSUE TITLE
can't connect to locally hosted database on linux

### ISSUE THREAD

**Issue by robertanton81** [motor-admin/motor-admin#62]
When trying to connect to locally hosted database, either from motor-admin running in docker, or locally, I am getting connection, or api error.
The api error is:
 `ERROR -- : [ae5063e7-fa9a-4112-987e-1fe12cd34989] uninitialized constant Api::VerifyDbConnectionController::PG
        PG.connect(url).close`
The connection url, produced by setup page of motor-admin was tested through psq in bash, and is used in other applications like datagrip, dbeaver or locally developed api.

Linux distro used: Pop!OS 22.04 LTS
Postgres version: DBMS: PostgreSQL (ver. 14.5 (Ubuntu 14.5-1.pgdg22.04+1))
Case sensitivity: plain=lower, delimited=exact

**Comment by omohokcoj** [comment]
@robertanton81 it seems like the PG native extension was not loaded because the binary was built for ubuntu 20.04 (assuming your example was outside docker).
But it should work in docker - did you receive the same error message when running in docker?
