### ISSUE TITLE
Downloading file from custom form

### ISSUE THREAD

**Issue by robertanton81** [motor-admin/motor-admin#66]
unfortunately issue #63 still does not seem to be resolved. No matter what settings are used to send the file from express.js app, the result is trying to display downloaded file. Using for example Postman to send and download request works as expected. 

![image](https://user-images.githubusercontent.com/18146018/196109461-4e152e2c-14dc-41c7-b800-69b53622c9e9.png)

**Comment by omohokcoj** [comment]
@robertanton81 did you set `Content-Disposition: attachment; filename="filename.jpg"` header for your file response?
Can you share the request/response details from browser network inspector?

**Comment by robertanton81** [comment]
how the response is sent: ```
res.set({
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename=${invoiceFileName}`,
      })

      res.send(file)
```
response headers: `Cache-Control: max-age=0, private, must-revalidate
Content-Type: text/html; charset=utf-8
ETag: W/"9eabe83527f4186498b157df6c1564c8"
Referrer-Policy: strict-origin-when-cross-origin
Set-Cookie: _motor_admin_session=...jibrish; path=/; HttpOnly; SameSite=Lax
Transfer-Encoding: chunked
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Request-Id: a06a77e5-37e6-4d43-8964-38d1794a1468
X-Runtime: 1.655696
X-XSS-Protection: 0`

**Comment by omohokcoj** [comment]
@robertanton81 there are no Content-Disposition header in your response and the content type is  `Content-Type: text/html`- idk how to set headers in express.js but the correct way to solve this it to set Content-Disposition header for the file response.

**Comment by robertanton81** [comment]
well, I see that. But tricky part is this one
![image](https://user-images.githubusercontent.com/18146018/196153598-3fdc3a7a-f0bd-46c6-923e-0387b4317ee9.png)

in the runtime I see those headers set correctly

**Comment by omohokcoj** [comment]
@robertanton81 maybe headers are overridden by reverse proxy/load balancer.
I think the correct way to debug it is via `curl -v http://localhost/file_path` - curl shows all headers as is.

**Comment by robertanton81** [comment]
I would guess you are right about the proxy, but that has to come from the docker container or something
` GET /api/admin/client-invoice/download-for-event/3735 HTTP/1.1
> Host: localhost:3001
> User-Agent: curl/7.82.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< X-Powered-By: Express
< Content-Type: application/pdf
< Content-Disposition: attachment; filename=4262022-00430.pdf
< Content-Length: 42719
< ETag: W/"a6df-NTiqaA9lzFMUJ+EpBMUYNNP3uG4"
< Date: Mon, 17 Oct 2022 10:32:31 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
`

**Comment by robertanton81** [comment]
might be related ? https://lucshelton.com/blog/securing-http-headers-with-nginx-in-docker/

**Comment by omohokcoj** [comment]
@robertanton81 sorry for the late reply - the curl output you shared was from `X-Powered-By: Express` but it also seems like your node app is under nginx reverse proxy. You need to make sure that requests sent to nginx return `Content-Disposition` header with all headers from the node server (seems like your nginx in misconfigured because it overrides all headers)
