### ISSUE TITLE
Pass current user to remote api form ?

### ISSUE THREAD

**Issue by revskill10** [motor-admin/motor-admin#7]
Hm, currently i don't see how i can get current user information when submitting the form to remote api . Any guidance on this ?

**Comment by omohokcoj** [comment]
@revskill10 Motor Admin sends JWT header automatically to the API for all custom forms and actions.
You can learn more about it here: 
https://github.com/motor-admin/motor-admin/blob/master/guides/building_custom_forms.md#authorizing-form

Also, you need to update to the latest 0.2.19 version to make JWT work.

**Comment by revskill10** [comment]
@omohokcoj I used SECRET_KEY_BASE as secret, but always receive error invalid signature

```js
jwt.verify(token, process.env.SECRET_KEY_BASE)
```

Am i missing something here ?

**Comment by revskill10** [comment]
@omohokcoj Could you please recheck this ? Should `SECRET_KEY_BASE` have some specical format ?

**Comment by omohokcoj** [comment]
@revskill10 did you copy SECRET_KEY_BASE from motor admin into your nodejs app?
SECRET_KEY_BASE in nodejs api app and motor admin should be identical to verity the token.

**Comment by revskill10** [comment]
@omohokcoj Yes, i copied the same , in this case, here's the key
```
f6360ad19d99e490dd562d0f26c901b66702e4428f48e606d95472ec88ca271c
```
You can test with nodejs `jsonwebtoken` and it failed.
That key above is autogenerated when i install on Heroku.

**Comment by omohokcoj** [comment]
@revskill10 can you send your nodejs code? are you sure you remove 'Baerer ' from the auth header?

**Comment by revskill10** [comment]
@omohokcoj The code is
```js
import jwt from 'jsonwebtoken';
const secret = process.env.SECRET_KEY_BASE;

export const verifyJwt = (req, res, next) => {
    const authorization = req.headers.authorization;
    console.log('authorization', authorization);
    if (!authorization) {
        res.status(400).json({})
    }
    const [_, token] = req.headers.authorization.split(' ')
    console.log('token', token);
    console.log('secret', secret)
    jwt.verify(token.toString(), process.env.SECRET_KEY_BASE, next);
}
```

**Comment by omohokcoj** [comment]
thanks, @revskill10 i has been fixed in the newest version - you can learn about how to update here:
https://github.com/motor-admin/motor-admin/releases/tag/latest
