### ISSUE TITLE
InvalidAuthenticityToken error

### ISSUE THREAD

**Issue by agentcobra** [motor-admin/motor-admin#75]
Hi,
I have this following error and cannot sign in.
![image](https://user-images.githubusercontent.com/1831853/213002809-6c804c32-1346-4386-a24e-936eaa598d1e.png)

in the console, I have this element :
```
ActionController::InvalidAuthenticityToken (HTTP Origin header (https://admin.***.fr) didn't match request.base_url (http://admin.***.fr)):
```
How can I fix it?
best regard

**Comment by omohokcoj** [comment]
@agentcobra did you run it from docker or as a rails app via `rails s` from the git cloned repo?
It seems like you're running the app in dev mode - it's best to use docker image so everything works out of the box - or use the boot script from `./bin/motor-admin`

**Comment by omohokcoj** [comment]
@agentcobra it seems like the issue is with your reverse proxy setup:
<img width="752" alt="image" src="https://user-images.githubusercontent.com/5418788/213007474-35e5cad2-f2f1-40ce-a0f4-78cd0748f6d1.png">
Need to make sure you have a properly configured reverse proxy headers (X-Forwarded-Protocol: https)

**Comment by agentcobra** [comment]
I have configured env file but it doesn't take configuration.
Have you have documentation to configure SSL on motor-admin?

**Comment by omohokcoj** [comment]
@agentcobra you can run motor-admin under SSL without reverse proxy server by specifying `SSL_KEY_PATH` and  `SSL_CERT_PATH` env variables. But keep in mind that you need to mount your ssl certs folder (letsencrypt certbot for instance) in docker container - `docker run -it -p 433:433 -v `pwd`:/app -v /certbot/live/domain.com:/cert/live/domain.com:ro motoradmin/motoradmin:latest`

But it probably would be best to use some reverse proxy - caddy allows to proxy requests with automatic ssl with a single command: https://caddyserver.com/docs/quick-starts/reverse-proxy#https-from-client-to-proxy

**Comment by omohokcoj** [comment]
This issue is most likely was caused by reverse proxy misconfigurations - so it's not related to motor-admin server.
