### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by lonnychetrit** [motor-admin/motor-admin#78]
Hi Guys, 
I'm unable to install the tool, I tried docker, docker-compose, and mac os install processes.

The docker container is up and running but I get a blank screen with this error message in the console
![Capture d’écran 2023-02-03 à 12 34 07](https://user-images.githubusercontent.com/39568930/216593604-a88c40fa-106a-4b58-9b08-23769c850a53.png)

Thanks

**Comment by omohokcoj** [comment]
@lonnychetrit .js and .css assets are loaded by your browser with text/html content type.
Are you using some reverse proxy on top of motor admin that overrides the correct content type to text/html?

**Comment by lonnychetrit** [comment]
Hi @omohokcoj 
No I'm not using any reverse proxy 
I think you can reproduce it by running the oneliner docker command and trying to open any browser 
If you want we can jump on a call so I could show you

**Comment by omohokcoj** [comment]
@lonnychetrit can you go to the network page to check the content of .js .css assets loaded on the page?
<img width="780" alt="image" src="https://user-images.githubusercontent.com/5418788/216781394-12924f36-d513-4cae-b669-3c4cfe7abb65.png">
maybe you already have something running on port 3000 and it conflicts with motor admin server

**Comment by lonnychetrit** [comment]
No I dont have anything running on the port and I can't see the content of
the js and css files since they are not downloaded

Aren't you able to reproduce?

Le sam. 4 févr. 2023 à 19:34, Pete Matsyburka ***@***.***> a
écrit :

**Comment by omohokcoj** [comment]
@lonnychetrit i'm not able to reproduce this - it might help a lot if you share the content of your "network" tab as well as the response from individual .js .css files

**Comment by lonnychetrit** [comment]
Hi
The files are not loaded so I can't see the content

Which version of docker are you using? This is weird

I'm using docker 18 on a mac


Le dim. 5 févr. 2023 à 12:58, Pete Matsyburka ***@***.***> a
écrit :

**Comment by lonnychetrit** [comment]
I've fixed the issue by upgrading the docker version of my mac to the Docker version 20.10.8

[SOLVED]
