### ISSUE TITLE
How to setup users role permissions? Seems doc is outdate

### ISSUE THREAD

**Issue by TangMonk** [motor-admin/motor-admin#80]
<img width="901" alt="image" src="https://user-images.githubusercontent.com/3498786/220921103-a29af795-f69d-4102-a5e7-6b72ba549d63.png">

The doc said can visit `http://localhost:3000/settings/roles` page, but not works

**Comment by omohokcoj** [comment]
@TangMonk the docs are correct on the https://docs.getmotoradmin.com/guide/roles_and_permissions.html
/settings/roles page is available in the latest docker release.

**Comment by TangMonk** [comment]
> @TangMonk the docs are correct on the https://docs.getmotoradmin.com/guide/roles_and_permissions.html /settings/roles page is available in the latest docker release.

is it only avaliable for paid users?

**Comment by TangMonk** [comment]
> @TangMonk the docs are correct on the https://docs.getmotoradmin.com/guide/roles_and_permissions.html /settings/roles page is available in the latest docker release.

And also, For your online demo, I cannot open `/setting/roles` and `/setting/users` page

**Comment by TangMonk** [comment]
sorry, I am using docker now
