### ISSUE TITLE
asset losts `/assets/main-947a9a9c3b6ed918c60d.js` when using nginx reverse proxy to serve static files

### ISSUE THREAD

**Issue by TangMonk** [motor-admin/motor-admin#82]
It seems`/assets/main-947a9a9c3b6ed918c60d.js` is dynamic generate by motor-admin, I can access it without using nginx reverse proxy, but not work using nginx.

**Comment by omohokcoj** [comment]
@TangMonk it must be caused by some nginx misconfigurations - it's hard to help to resolve those issues because they are not related to motor-admin server. I'd recommend you to try caddy reverse proxy if possible - it allows to run a reverse proxy server with auto ssl with a single command.
