### ISSUE TITLE
API based data-sources for custom application, domain and authorization logic

### ISSUE THREAD

**Issue by kravemir** [motor-admin/motor-admin#83]
I am searching for a model-driven UI and found Motor Admin.

However, Motor Admin seems to be more than just an admin panel UI, but also a backend, which integrates a bit too low - directly with persistence layer, and implements own access control.

Is it possible to integrate Motor Admin on top of an existing API, which provides metadata about structure of entities and available commands, by implementing some adapter? I.e.:

1. Motor Admin for UI layer:
   - custom adapter implementation transforming API's model metadata to Motor Admin definitions,
2. custom Application API:
   - provides model metadata and schema,
   - provides data query and command endpoints,
3. custom Application access control layer:
   - ABAC, ReBAC or any else
4. custom Application domain logic layer,
5. custom Application persistence Layer.

To be honest, I had already implemented such model-driven UI-only panel on my own. However, it's a bit of ugly piece of code, and not published. Also, it's hard-coded to support exactly one type of model schema metadata API - not supporting adapters for custom API. And, so I'm researching open-source solutions to not reinvent the wheel, if it's already invented / implemented.

**Comment by omohokcoj** [comment]
>Is it possible to integrate Motor Admin on top of an existing API

@kravemir unfortunately no - and that's not going to be in scope of motor-admin in the foreseeable future.
I'd recommend you to try Tooljet or Budibase - they work better with APIs but it usually takes more time to configure everything with APIs comparing to a direct DB connection.
