### ISSUE TITLE
Fails to load resources if column name is defined by Active Record

### ISSUE THREAD

**Issue by sananguliyev** [motor-admin/motor-admin#84]
I have the table which has column name `model_name` and it throws this error:

```
model_name is defined by Active Record. Check to make sure that you don't have an attribute or method with the same name.
```

**Comment by sananguliyev** [comment]
@omohokcoj thanks for the quick fix. I hope the changes you made solves all those kinds of issues. May I ask when are you planning to release `0.4.7`?

**Comment by omohokcoj** [comment]
@sananguliyev the latest `0.4.7` docker version has been updated with this fix.
Fyi - this fix removes reserved columns from the motor admin resource table - so with it the table should work but still you won't be able to access/update your `model_name` column.

**Comment by sananguliyev** [comment]
Is there any way to fix the issue, at least access to field?

**Comment by omohokcoj** [comment]
@sananguliyev i was not able to find a way to make it possible to access those fields - seems like the only way is to rename the column in the DB
