### ISSUE TITLE
Cant create reports/save queries with remote MYSQL. 

### ISSUE THREAD

**Issue by fulfillmen** [motor-admin/motor-admin#85]
Been trying to setup reports with a remote mysql db, the connection works, the tables are visible in the sidebar but when I try to create a query for the reports it shows "SQLite3::SQLException: no such table: "

**Comment by fulfillmen** [comment]
Update: 

Thought its some config error so I restart the container, now its showing a different error:

STATEMENT:  SELECT "__query__".* FROM (SELECT `TABLENAME`.* FROM `TABLENAME`) AS "__query__" LIMIT 20

**Comment by omohokcoj** [comment]
STATEMENT: SELECT "query".* FROM (SELECT TABLENAME.* FROM TABLENAME) AS "query" LIMIT 20

@fulfillmen it seems like an error in your sql custom sql - "query" is not a valid mysql syntax - use \`query\` instead

**Comment by fulfillmen** [comment]
HI, 

thank you for the response, I am using the proper sql query, attached the ss
<img width="1431" alt="Screenshot 2023-03-04 at 7 12 09 PM" src="https://user-images.githubusercontent.com/68221219/222905774-2d70c14e-81cc-446b-8af5-5d7e6800b350.png">
 as well.

**Comment by omohokcoj** [comment]
@fulfillmen are you sure that your `forwarderdata` table exists in the corrected database?
Can you try `SHOW TABLES` to check which tables exists?

**Comment by fulfillmen** [comment]
it exists, I am woking on those tables for more than 3 years. :)

**Comment by fulfillmen** [comment]
<img width="1433" alt="Screenshot 2023-03-06 at 8 22 35 AM" src="https://user-images.githubusercontent.com/68221219/223008613-57b863a0-5ee5-474f-a110-78ac0cfbfc08.png">


There is an issue with it.

**Comment by fulfillmen** [comment]
<img width="817" alt="Screenshot 2023-03-06 at 3 05 49 PM" src="https://user-images.githubusercontent.com/68221219/223072291-ff045aa2-b794-4ef0-8e52-76b8408dfaa7.png">
seems like it's not gonna work. I have deleted the container and tried with a fresh start but it's not working.

**Comment by fulfillmen** [comment]
Since the mysql method isn't working, i am trying to setup api, is it possible to send Custom request header along with the api call?

**Comment by omohokcoj** [comment]
@fulfillmen i'm not able to reproduce the issue - everything works well in the latest docker 0.4.7 release and mysql8 server.
Which version of mysql are you using?
