### ISSUE TITLE
Can't audits database opration history

### ISSUE THREAD

**Issue by ciscolive** [motor-admin/motor-admin#86]
Dear motor-admin, I tried to use this project recently, and found that the user's operation log cannot be audited normally after starting it. Is there a bug in this project or does it need special configuration?

**Comment by ciscolive** [comment]
![motor_admin](https://user-images.githubusercontent.com/20869208/224481238-1a6c32b4-1a1f-4131-9258-380800faf5ce.png)
But login with crates@qq.com, and created data

**Comment by omohokcoj** [comment]
@ciscolive it has been fixed in the latest 0.4.8 release

**Comment by ciscolive** [comment]
Thank you so much
