### ISSUE TITLE
Unable to set other database field is required attribute

### ISSUE THREAD

**Issue by ciscolive** [motor-admin/motor-admin#87]
Dear motor-admin, does it currently support the function of connecting to other databases and setting required attributes? If this function is not supported, data integrity cannot be guaranteed. I hope this function can be added in the future, thank you！

local rails project set model validates can't work in motor-admin 
![motor_local](https://user-images.githubusercontent.com/20869208/224522216-66ed29fc-455b-48bf-b803-ef7ef7fd1616.png)

**Comment by ciscolive** [comment]
![motor_5000](https://user-images.githubusercontent.com/20869208/224522256-c01efb09-5382-4f57-8876-528a50b718b3.png)

with motor-admin, model's validates can't working 

```ruby
class Viper < ApplicationRecord
  # 必填属性
  validates :name, :email, :ip, :mac, :sys_os, presence: true
  validates :ip, format: { with: Resolv::IPv4::Regex, message: 'Invalid IP address' }
  validates :mac, presence: true, uniqueness: true, format: { with: /\A([0-9A-Fa-f]{2}[:-]){5}[0-9A-Fa-f]{2}\z/, message: "Invalid MAC address" }

  scope :latest, -> { where 'date(created_at) = ?', Date.today }

  scope :yesterday, -> { where 'date(created_at) = ?', Date.yesterday }
end
```

**Comment by ciscolive** [comment]
rails model with  validates :sys_os, inclusion: { in: %w[WINDOWS MACOS LINUX] } can't working with multidatabase also

**Comment by omohokcoj** [comment]
@ciscolive rails validations work with motor-admin-rails gem. standalone motor-admin works with databases and doesn't know anything about rails application validations
