### ISSUE TITLE
Fuzzy search does not support pgsql inet macaddr fields

### ISSUE THREAD

**Issue by ciscolive** [motor-admin/motor-admin#88]
Seems motor-admin can't support postgresql inet macaddr cidr blur search
![2023-03-12 11-41-04 的屏幕截图](https://user-images.githubusercontent.com/20869208/224522963-35cecd28-c54f-4361-9e7d-8b932949ce9e.png)

**Comment by omohokcoj** [comment]
@ciscolive it's hard to make full text search work both with inet and macaddr at the same time since they require a specific format. Instead if would be best to remove those column from your full text search and use filters to find by ip/mac
