### ISSUE TITLE
Rails couldn't find a valid model for AlertTemplates association

### ISSUE THREAD

**Issue by ciscolive** [motor-admin/motor-admin#91]
Dear administrator
    I encountered an error while adding the database for the open source project librenms and am unable to resolve it on my own. Could you please help me take a look at how to fix it when you have time? Thank you.

error info: NameError in Motor::UiController#show
![2023-03-16 21-19-26 的屏幕截图](https://user-images.githubusercontent.com/20869208/225629371-866f88cc-4448-4f49-9e8b-a675af01d656.png)

* librenms database
 https://librenms.org/

**Comment by omohokcoj** [comment]
@ciscolive it seems like you're using some fork of motor admin running in development mode - it's hard to find out what happens here when your code might contain some modifications that are not in the upstream repository.

Try to run the same database using docker production release of motor admin - hopefully it works there.
