### ISSUE TITLE
Allow setting a max age for the login cookie to limit session length

### ISSUE THREAD

**Issue by wodow** [motor-admin/motor-admin#95]
Currently the cookie has `Max-Age: Session`, whereas it would be useful / essential to limit this in some environments.

**Comment by omohokcoj** [comment]
@wodow you can use reverse proxy (caddy traefik nginx) to override cookies header max-age:
https://caddyserver.com/docs/caddyfile/directives/header
It's very unlikely that many motor admin users will find this additional cookies configuration useful - i'd say we should leave the default cookies max age as is.
Also there is a Pro version for better security/authentication.
