### ISSUE TITLE
how to change date field format

### ISSUE THREAD

**Issue by TangMonk** [motor-admin/motor-admin#96]
<img width="334" alt="image" src="https://github.com/motor-admin/motor-admin/assets/3498786/f8ff7586-1efe-4c95-b55d-17d21a94e24f">
I wannt to use YYYY-MM-DD format to show date field

**Comment by omohokcoj** [comment]
@TangMonk date/time format is utilizing a native `Intl` api - so this way users with en_US browser locale see dates in the US format and users in de_DE locale - in German date/time format - there are no plans to change it or make customizable.
