### ISSUE TITLE
how to disable user to edit setting

### ISSUE THREAD

**Issue by TangMonk** [motor-admin/motor-admin#97]
<img width="59" alt="image" src="https://github.com/motor-admin/motor-admin/assets/3498786/8ea5ea4e-a135-413b-8bac-4ac26133397c">
This setting button can edit anything, How to disable this button for normal users?

**Comment by omohokcoj** [comment]
@TangMonk only users with 'manage all' role permission can see it:
https://docs.getmotoradmin.com/guide/roles_and_permissions.html#defining-role-permissions
